AWSTemplateFormatVersion: 2010-09-09
Description: EKS Cluster with NLB, Target Group, and Listener

Parameters:
  VpcId:
    Type: String
    Description: Existing VPC ID
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for EKS and NLB
  ClusterName:
    Type: String
    Default: eks-demo-cluster
  NodeInstanceType:
    Type: String
    Default: t3.medium
  DesiredCapacity:
    Type: Number
    Default: 2
  MaxSize:
    Type: Number
    Default: 3
  MinSize:
    Type: Number
    Default: 2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair for worker nodes

Resources:

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        SecurityGroupIds: []
      Version: "1.30"

  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

  NodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref NodeInstanceRole

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: EKSCluster
    Properties:
      ClusterName: !Ref ClusterName
      NodeRole: !GetAtt NodeInstanceRole.Arn
      ScalingConfig:
        DesiredSize: !Ref DesiredCapacity
        MaxSize: !Ref MaxSize
        MinSize: !Ref MinSize
      Subnets: !Ref SubnetIds
      InstanceTypes:
        - !Ref NodeInstanceType
      AmiType: AL2_x86_64
      RemoteAccess:
        Ec2SshKey: !Ref KeyName

  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: eks-nlb
      Type: network
      Scheme: internet-facing
      Subnets: !Ref SubnetIds

  NLBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 30080
      Protocol: TCP
      TargetType: instance
      HealthCheckProtocol: TCP

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref NLBTargetGroup

Outputs:
  EKSClusterName:
    Value: !Ref EKSCluster
    Export:
      Name: EKSClusterName
  NLBDNSName:
    Value: !GetAtt NLB.DNSName
    Export:
      Name: NLBDNSName