AWSTemplateFormatVersion: "2010-09-09"
Description: >
  VPC (10.0.0.0/24) with one Public Subnet and one Private Subnet.
  DNS resolution and hostnames enabled.
  Public route table is set as main, and an EC2 instance is launched in the Public Subnet
  with Apache installed via UserData.

Parameters:
  KeyNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance

Resources:

  # VPC with DNS attributes enabled
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc"

  # Public subnet (first half of /24)
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/25
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-subnet"

  # Private subnet (second half of /24)
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.128/25
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-subnet"

  # Internet Gateway and attachment
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-igw"

  AttachInternetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  # Public route table (will be set as main)
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-rt"

  # Default route in public route table
  PublicDefaultRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachInternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Set Public RT as Main RT
  SetMainRouteTable:
    Type: AWS::EC2::VPCRouteTableAssociation
    Properties:
      VpcId: !Ref MyVPC
      RouteTableId: !Ref PublicRouteTable

  # Security group for EC2 instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH, ICMP, and HTTP access
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-sg"

  # Latest Amazon Linux 2 AMI via SSM Parameter
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  # EC2 instance in Public Subnet
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: c6a.large
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      KeyName: !Ref KeyNameParameter
      ImageId: !Ref LatestAmiId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          # ---- Option 1: Apache ----
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Hello from Apache on EC2 in ${AWS::StackName}</h1>" > /var/www/html/index.html

          # ---- Option 2: Nginx (comment Apache section above if you prefer) ----
          # amazon-linux-extras enable nginx1
          # yum install -y nginx
          # systemctl enable nginx
          # systemctl start nginx
          # echo "<h1>Hello from Nginx on EC2 in ${AWS::StackName}</h1>" > /usr/share/nginx/html/index.html
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ec2"

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref MyVPC

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet

  EC2InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance
