# pod-using-pvc.yaml
apiVersion: v1
kind: Pod
metadata:
  name: pvc-test-pod
  namespace: default
spec:
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c", "sleep 3600" ]   # keep pod running
      volumeMounts:
        - mountPath: /data
          name: pvc-storage
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: demo-pvc
