apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-static
  awsElasticBlockStore:
    volumeID: <EBS_VOLUME_ID>   # You must create this EBS volume in AWS first
    fsType: ext4
