apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.9
          ports:
            - containerPort: 7687
            - containerPort: 7473
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test"
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-pvc
