apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - name: bolt-tcp
      protocol: TCP
      port: 7687
      targetPort: 7687
    - name: bolt-https
      protocol: TCP
      port: 7473
      targetPort: 7473
